import type { Config } from "tailwindcss";

// Transcribed 1:1 from kuditask_engine/DESIGN.md — do not hand-tune these
// values, edit DESIGN.md's source of truth and regenerate instead.
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#404942",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        outline: "#707972",
        "outline-variant": "#bfc9c0",
        "surface-tint": "#2a6a49",
        primary: "#003620",
        "on-primary": "#ffffff",
        "primary-container": "#054f31",
        "on-primary-container": "#7fc099",
        "inverse-primary": "#93d5ad",
        secondary: "#006c47",
        "on-secondary": "#ffffff",
        "secondary-container": "#8af5be",
        "on-secondary-container": "#00714b",
        tertiary: "#003623",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#004f34",
        "on-tertiary-container": "#31c98f",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#aef1c8",
        "primary-fixed-dim": "#93d5ad",
        "on-primary-fixed": "#002111",
        "on-primary-fixed-variant": "#095133",
        "secondary-fixed": "#8df7c1",
        "secondary-fixed-dim": "#71dba6",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005235",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        background: "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        // Functional semantics (status colors), named separately from the
        // Material-style roles above so components can reach for them directly.
        "status-settled-fg": "#059669",
        "status-settled-bg": "#ecfdf5",
        "status-warning-fg": "#d97706",
        "status-warning-bg": "#fffbeb",
        "status-error-fg": "#dc2626",
        "status-error-bg": "#fef2f2",
        "status-info-fg": "#2563eb",
        "status-info-bg": "#eff6ff",
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk"],
        "headline-xl-mobile": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "headline-sm": ["Space Grotesk"],
        "title-md": ["Plus Jakarta Sans"],
        "title-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-lg": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "label-sm": ["Space Grotesk"],
        "currency-display": ["Space Grotesk"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "700" }],
        "currency-display": ["36px", { lineHeight: "44px", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-desktop": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
    },
  },
  plugins: [],
};

export default config;
